### ISSUE TITLE
Pandas.DataFrame.to_csv() unexpected argument sparsify

### ISSUE THREAD

**Issue by kwkroll32** [blachlylab/mucor#12]
Received an error writing vcf output. Apparently pandas.DataFrame.to_csv() doesn't accept the "sparsify" argument (anymore?). Not sure what it is supposed to do, but commenting it out stops the error and still produces a vcf file. If we can't remember where this came from, I propose we remove that argument from this particular to_csv call. 

Pandas 0.19.1
See the offending line in output.VCF [here](https://github.com/blachlylab/mucor/blob/master/output.py#L399)
<pre>
Traceback (most recent call last):
  File "/home/karl/Tools/mucor/mucor.py", line 699, in <module>
    main()
  File "/home/karl/Tools/mucor/mucor.py", line 690, in main
    printOutput(config, str(config.outputDir), varDF)
  File "/home/karl/Tools/mucor/mucor.py", line 649, in printOutput
    ow.write(varDF,format,outputDirName,config)
  File "/home/karl/Tools/mucor/output.py", line 95, in write
    self.supported_formats[format]()
  File "/home/karl/Tools/mucor/output.py", line 399, in VCF
    out.to_csv(ofVariantVCF, sep='\t', na_rep='?', index=False, header=True, sparsify=False)
TypeError: to_csv() got an unexpected keyword argument 'sparsify'
</pre>

**Comment by jblachly** [comment]
I can’t even find this parameter in the OLD version of pandas documentation. . Probably was undocumented parameter — how did you even find it? . Agree with removing but need to figure out what it will do. pandas manual has a section of sparsified data structures. HAs to do , I think, with multi-indices.

**Comment by kwkroll32** [comment]
I got that error by simply trying to write vcf output. Something about my current environment must be different than before - Pandas 0.17 vs 0.19 maybe?
